name: hand-gesture
channels:
  - defaults
  - conda-forge
  - open3d-admin
dependencies:
  - pip=22.3.1
  - python=3.8.10
  - numpy=1.24.4
  - pip:
    - absl-py==1.4.0
    - altgraph==0.17.3
    - attrs==23.1.0
    - autopy==4.0.0
    - cffi==1.15.1
    - contourpy==1.1.0
    - cvzone==1.5.6
    - cycler==0.11.0
    - EasyProcess==1.1
    - entrypoint2==1.1
    - flatbuffers==23.5.26
    - fonttools==4.41.1
    - importlib-resources==6.0.0
    - kiwisolver==1.4.4
    - matplotlib==3.7.2
    - mediapipe==0.10.2
    - MouseInfo==0.1.3
    - mss==9.0.1
    - numpy==1.24.4
    - opencv-contrib-python==4.8.0.74
    - opencv-python==4.8.0.74
    - packaging==23.1
    - pefile==2023.2.7
    - Pillow==10.0.0
    - protobuf==3.20.3
    - PyAutoGUI==0.9.54
    - pycparser==2.21
    - PyGetWindow==0.0.9
    - pyinstaller==5.13.0
    - pyinstaller-hooks-contrib==2023.6
    - PyMsgBox==1.0.9
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - PyRect==0.2.0
    - pyscreenshot==3.1
    - PyScreeze==0.1.29
    - python-dateutil==2.8.2
    - pytweening==1.0.7
    - pywin32-ctypes==0.2.2
    - six==1.16.0
    - sounddevice==0.4.6
    - zipp==3.16.2